NULL_BLANK: dict[str, bool] = {
    "null": True,
    "blank": True,
}
SERVICE_TITLE_LEN: int = 128
SERVICE_PREVIEW_SIZE: tuple[int, int] = (1280, 720)
SERVICE_PREVIEW_QUALITY_PERCENT: int = 95
SERVICE_PREVIEW_ALT_TEXT_LEN: int = 20
ADVANTAGE_TITLE_LEN: int = 60
ADVANTAGE_ICON_CLASS_LEN: int = 255
SLIDE_IMAGE_SIZE: tuple[int, int] = (1280, 720)
SLIDE_IMAGE_QUALITY_PERCENT: int = 95
REVIEW_AUTHOR_NAME_LEN: int = 60
REVIEW_AUTHOR_AVATAR_QUALITY_PERCENT: int = 95
REVIEW_AUTHOR_AVATAR_SIZE: tuple[int, int] = (60, 60)
EMPLOYEE_IMAGE_SIZE: tuple[int, int] = (120, 120)
EMPLOYEE_IMAGE_QUALITY_PERCENT: int = 100
EMPLOYEE_FIRST_NAME_LEN: int = 30
EMPLOYEE_LAST_NAME_LEN: int = 30
POSITION_NANE_LEN: int = 20
ACHIEVEMENT_TITLE_LEN: int = 60
